---
web:
  port: 7000

###################
# sqlite connection
###################
# database:
#   type: sqlite
#   connectionUrl: "file:./expense.dev.db"


###################
# psql connectoin #
###################
database:
  type: "postgres"
  connectionUrl: "postgresql://app:test@alma9.home:30432/app?sslmode=require"

jwt:
  maxAgeHours: 4
  signingKey: "keymaker"
