# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Cr:eated with podman-4.6.2
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-09-02T15:30:25Z"
  labels:
    app: sso
  name: sso
spec:
  containers:
  - name: "database"
    image: quay.io/centos7/postgresql-10-centos7:latest
    ports:
      - containerPort: 5432
        hostPort: 5432
    env:
    - name: POSTGRESQL_USER
      value: keycloak
    - name: POSTGRESQL_PASSWORD
      value: keycloak
    - name: POSTGRESQL_DATABASE
      value: root

  
  - name: "keycloak"
    image:  "quay.io/nmajorov/sso:7.6.5"
    ports:
      - containerPort: 8080
        hostPort: 7080
      - containerPort: 5432
        hostPort: 5432
    env:
    - name: DB_USER
      value: keycloak
    - name: DB_PASSWORD
      value: keycloak
    - name: DB_DATABASE
      value: root
    - name: DB_ADDR
      value: localhost:5432
