apiVersion: v1
kind: ConfigMap
metadata:
  name: expense-app-backend-config
  labels:
    app: expense-app-backend
data:
  config.yaml: |
    web:
      port: 7000

    database:
      type: "postgres"
      connectionUrl: "postgresql://app:test@alma9.home:30432/app?sslmode=require"

    jwt:
      maxAgeHours: 4
      signingKey: "changeme"
