apiVersion: v1
kind: ConfigMap
metadata:
  name: expense-app-backend-config
  labels:
    app: expense-app-backend
data:
  config.yaml: |
    web:
      port: 7000

    database:
      type: "sqlite3"
      connectionUrl: "file:/data/expense.db"

    jwt:
      maxAgeHours: 4
      signingKey: "changeme"
