apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expense-app-backend-data
  labels:
    app: expense-app-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
