apiVersion:  tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: backend-run-developement-branch
spec:
  params:
    - name: git-revision
      value: "development"
    - name: keycloak_url
      # for sso 7.6 without /auth 
      value: "https://keycloak-nm-sso.apps.ocp001.rhlab.ch"
     # backend database parameters
    - name: postgesql-user
      value: "keycloak"
    - name: postgresql-password
      value: "keycloak"
    - name: postresql-database
      value: "root"
    - name: database-service-name
      value: "knm"

  pipelineRef:
    name: build-and-deploy-backend
  workspaces:
  - name: shared-workspace
    persistentVolumeClaim:
      claimName: source-pvc
